//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class estimateslines
    {
        public int estimateslines_id { get; set; }
        public int estimates_id { get; set; }
        public Nullable<int> patientstreatments_id { get; set; }
        public string estimateslines_code { get; set; }
        public string estimateslines_description { get; set; }
        public int estimateslines_quantity { get; set; }
        public decimal estimateslines_unitprice { get; set; }
        public decimal estimateslines_taxrate { get; set; }
        public bool estimateslines_istaxesdeductionsable { get; set; }
    
        public virtual estimates estimates { get; set; }
        public virtual patientstreatments patientstreatments { get; set; }
    }
}
