//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class patientsaddresses
    {
        public int patientsaddresses_id { get; set; }
        public int patients_id { get; set; }
        public int addressestypes_id { get; set; }
        public string patientsaddresses_state { get; set; }
        public string patientsaddresses_city { get; set; }
        public string patientsaddresses_zipcode { get; set; }
        public string patientsaddresses_street { get; set; }
    
        public virtual addressestypes addressestypes { get; set; }
        public virtual patients patients { get; set; }
    }
}
