//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rooms
    {
        public rooms()
        {
            this.appointments = new HashSet<appointments>();
        }
    
        public int rooms_id { get; set; }
        public string rooms_name { get; set; }
        public string rooms_color { get; set; }
    
        public virtual ICollection<appointments> appointments { get; set; }
    }
}
