//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class addressestypes
    {
        public addressestypes()
        {
            this.patientsaddresses = new HashSet<patientsaddresses>();
        }
    
        public int addressestypes_id { get; set; }
        public string addressestypes_name { get; set; }
    
        public virtual ICollection<patientsaddresses> patientsaddresses { get; set; }
    }
}
