//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointments
    {
        public int appointments_id { get; set; }
        public int doctors_id { get; set; }
        public int patients_id { get; set; }
        public int rooms_id { get; set; }
        public System.DateTime appointments_from { get; set; }
        public System.DateTime appointments_to { get; set; }
        public string appointments_title { get; set; }
        public string appointments_notes { get; set; }
    
        public virtual doctors doctors { get; set; }
        public virtual patients patients { get; set; }
        public virtual rooms rooms { get; set; }
    }
}
