//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctors
    {
        public doctors()
        {
            this.appointments = new HashSet<appointments>();
            this.estimates = new HashSet<estimates>();
            this.invoices = new HashSet<invoices>();
            this.patientstreatments = new HashSet<patientstreatments>();
        }
    
        public int doctors_id { get; set; }
        public string doctors_name { get; set; }
        public string doctors_surname { get; set; }
        public string doctors_doctext { get; set; }
        public string doctors_username { get; set; }
        public string doctors_password { get; set; }
        public string doctors_token { get; set; }
        public Nullable<System.DateTime> doctors_lastlogin { get; set; }
    
        public virtual ICollection<appointments> appointments { get; set; }
        public virtual ICollection<estimates> estimates { get; set; }
        public virtual ICollection<invoices> invoices { get; set; }
        public virtual ICollection<patientstreatments> patientstreatments { get; set; }
    }
}
