//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoicesfooters
    {
        public int invoicesfooters_id { get; set; }
        public string invoicesfooters_name { get; set; }
        public string invoicesfooters_doctext { get; set; }
        public bool invoicesfooters_isdefault { get; set; }
    }
}
