//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceslines
    {
        public int invoiceslines_id { get; set; }
        public int invoices_id { get; set; }
        public Nullable<int> patientstreatments_id { get; set; }
        public string invoiceslines_code { get; set; }
        public string invoiceslines_description { get; set; }
        public int invoiceslines_quantity { get; set; }
        public decimal invoiceslines_unitprice { get; set; }
        public decimal invoiceslines_taxrate { get; set; }
        public bool invoiceslines_istaxesdeductionsable { get; set; }
    
        public virtual invoices invoices { get; set; }
        public virtual patientstreatments patientstreatments { get; set; }
    }
}
