//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicalrecordstypes
    {
        public medicalrecordstypes()
        {
            this.patientsmedicalrecords = new HashSet<patientsmedicalrecords>();
        }
    
        public int medicalrecordstypes_id { get; set; }
        public string medicalrecordstypes_name { get; set; }
    
        public virtual ICollection<patientsmedicalrecords> patientsmedicalrecords { get; set; }
    }
}
