//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentstypes
    {
        public int paymentstypes_id { get; set; }
        public string paymentstypes_name { get; set; }
        public string paymentstypes_doctext { get; set; }
        public bool paymentstypes_isdefault { get; set; }
    }
}
