//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxesdeductions
    {
        public int taxesdeductions_id { get; set; }
        public string taxesdeductions_name { get; set; }
        public decimal taxesdeductions_rate { get; set; }
        public bool taxesdeductions_isdefault { get; set; }
    }
}
