//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxes
    {
        public taxes()
        {
            this.computedlines = new HashSet<computedlines>();
            this.treatments = new HashSet<treatments>();
        }
    
        public int taxes_id { get; set; }
        public string taxes_name { get; set; }
        public decimal taxes_rate { get; set; }
        public bool taxes_isdefault { get; set; }
    
        public virtual ICollection<computedlines> computedlines { get; set; }
        public virtual ICollection<treatments> treatments { get; set; }
    }
}
