//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatments
    {
        public treatments()
        {
            this.patientstreatments = new HashSet<patientstreatments>();
            this.treatmentsprices = new HashSet<treatmentsprices>();
        }
    
        public int treatments_id { get; set; }
        public int treatmentstypes_id { get; set; }
        public string treatments_code { get; set; }
        public string treatments_name { get; set; }
        public decimal treatments_price { get; set; }
        public Nullable<byte> treatments_mexpiration { get; set; }
        public string treatments_notes { get; set; }
    
        public virtual ICollection<patientstreatments> patientstreatments { get; set; }
        public virtual treatmentstypes treatmentstypes { get; set; }
        public virtual ICollection<treatmentsprices> treatmentsprices { get; set; }
    }
}
