//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.DentneD.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatmentsprices
    {
        public int treatmentsprices_id { get; set; }
        public int treatments_id { get; set; }
        public int treatmentspriceslists_id { get; set; }
        public decimal treatmentsprices_price { get; set; }
    
        public virtual treatments treatments { get; set; }
        public virtual treatmentspriceslists treatmentspriceslists { get; set; }
    }
}
